routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::model('daylogs', 'Daylog');
Route::model('tasks', 'Task');

Route::bind('daylogs', function($value, $route) {
    return App\Daylog::whereSlug($value)->first();
});

Route::bind('tasks', function($value, $route) {
    return App\Task::whereSlug($value)->first();
});

Route::resource('daylogs', 'DaylogController');
Route::resource('daylogs.tasks', 'TaskController');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

app/Daylog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Daylog extends Model
{
    protected $table = 'daylogs';

    protected $guarded = [];

    /**
     * Get the route key for the model
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function tasks()
    {
        return $this->hasMany('App\Task');
    }
}

app/Http/Controllers/DayLogController.php
<?php

namespace App\Http\Controllers;

use App\Daylog;
use ControllerHelper;
use Request;

class DaylogController extends Controller
{
    private function getRules($daylog = null)
    {
        $rules = [
            'title' => 'required|max:1024',
            'slug' => 'required|max:255',
            'location' => 'required|max:255',
            'log_at' => 'required|date_format:Y-m-d|unique:daylogs,log_at'
                . (isset($daylog) ? ','.$daylog->id : ''),
            'category' => 'required|in:ADEQUATE,MINOR,MAJOR',
        ];

        return $rules;
    }

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $daylogs = Daylog::all()->where('user_id', \Auth::user()->id);
        return view('daylogs.index', compact('daylogs'));
    }

    public function show(Daylog $daylog)
    {
        return view('daylogs.show', compact('daylog'));
    }

    public function create()
    {
        return view('daylogs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return Response
     */
    public function store(\Illuminate\Http\Request $request)
    {
        $this->validate($request, $this->getRules());

        $input = Request::all();
        $input['user_id'] = \Auth::user()->id;
        Daylog::create( $input );

        return redirect('daylogs')->with('message',
            ControllerHelper::getNotificationMessage(Daylog::class, $request->title, 'created'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Daylog $daylog
     * @return Response
     */
    public function edit(Daylog $daylog)
    {
        return view('daylogs.edit', compact('daylog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Daylog $daylog
     * @param \Illuminate\Http\Request $request
     * @return Response
     */
    public function update(Daylog $daylog, \Illuminate\Http\Request $request)
    {
        $this->validate($request, $this->getRules($daylog));

        $input = array_except(Request::all(), '_method');
        $daylog->update($input);

        return redirect('daylogs/'.$daylog->slug)->with('message',
            ControllerHelper::getNotificationMessage(Daylog::class, $daylog->title, 'updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Daylog $daylog
     * @return Response
     */
    public function destroy(Daylog $daylog)
    {
        $title = $daylog->title;
        $daylog->delete();

        return redirect('daylogs')->with('message',
            ControllerHelper::getNotificationMessage(Daylog::class, $title, 'deleted'));
    }
}

resources/views/daylogs/create.blade.php
@extends('layouts.app')

@section('content')

    @include('layouts.daylog',
    [
        'method' => 'Create',
        'model' => new App\Daylog,
        'formAttributes' => ['route' => ['daylogs.store']],
    ])
@endsection

resources/views/daylogs/edit.blade.php
@extends('layouts.app')

@section('content')

    @include('layouts.daylog',
    [
        'method' => 'Edit',
        'model' => $daylog,
        'formAttributes' =>
            [
                'method' => 'PATCH',
                'route' => ['daylogs.update', $daylog->slug]
            ],
    ])
@endsection

resources/views/daylogs/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading"><h3>Day Logs</h3></div>

        <div class="panel-body">
            @if ( !$daylogs->count() )
            <div class="alert alert-info" role="alert">
                You have no Day Logs.
            </div>
            @else

                <table class="table" id="daylogs">
                    <thead>
                        <tr>
                            <th width="75%">Title</th>
                            <th class="text-right">Date</th>
                            <th class="text-right">Tasks</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach( $daylogs as $daylog )
                            <tr data-slug="{{ $daylog->slug }}">
                                <td>
                                    <a href="{{ route('daylogs.show', $daylog->slug) }}">
                                        {{ $daylog->title }}
                                    </a>
                                </td>
                                <td class="text-right">
                                    <code>{{ $daylog->log_at }}</code>
                                </td>
                                <td class="text-right">
                                    <code>{{ $daylog->tasks->count() }}</code>
                                </td>
                                <td>
                                    <a href="{{ route('daylogs.edit', $daylog->slug) }}"
                                        class="btn btn-primary btn-xs">
                                        Edit
                                    </a>
                                </td>
                                <td>
                                    {!! Form::open(
                                    [
                                        'class' => 'form-inline',
                                        'method' => 'DELETE',
                                        'route' => ['daylogs.destroy', $daylog->slug]
                                    ]) !!}
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            Delete
                                        </button>
                                    {!! Form::close() !!}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

            @endif
        </div>

        <div class="panel-footer">
            <p class="text-center">
                <a href="{{ route('daylogs.create') }}" class="btn btn-primary">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                     Create Day Log
                </a>
            </p>
        </div>
    </div>
@endsection

resources/views/daylogs/show.blade.php
@extends('layouts.app')

@section('content')

    @include('layouts.daylog',
    [
        'method' => 'View',
        'model' => $daylog,
        'formAttributes' => ['method' => 'GET'],
        'partialsAttributes' => ['isView' => true],
        'isView' => true,
    ])

    <div class="panel panel-default">
        <div class="panel-body">
            <h4 class="list-group-item-heading">Tasks</h4>
            @if ( $daylog->tasks->count() )
                <table class="table" id="tasks">
                    <thead>
                        <th>Title</th>
                        <th></th>
                        <th></th>
                    </thead>
                    <tbody>
                        @foreach( $daylog->tasks as $task )
                            <tr data-slug="{{ $task->slug }}">
                                <td>
                                    <a href="{{ route('daylogs.tasks.show',
                                        [$daylog->slug, $task->slug]) }}">
                                        {{ $task->title }}
                                    </a>
                                </td>
                                <td>
                                    {!! link_to_route('daylogs.tasks.edit', 'Edit',
                                        [$daylog->slug, $task->slug],
                                        ['class' => 'btn btn-info btn-xs']
                                    ) !!}
                                </td>
                                <td>
                                    {!! Form::open(
                                        [
                                            'class' => 'form-inline',
                                            'method' => 'DELETE',
                                            'route' => ['daylogs.tasks.destroy',
                                                $daylog->slug, $task->slug],
                                        ]) !!}
                                        {!! Form::submit('Delete',
                                            ['class' => 'btn btn-danger btn-xs']) !!}
                                    {!! Form::close() !!}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                <div class="alert alert-info">Your daylog has no tasks.</div>
            @endif
        </div>

        <div class="panel-footer">
            <p class="text-center">
                <a href="{{ route('daylogs.index') }}" role="button" class="btn btn-primary">
                    Back
                </a>
                <a href="/daylogs/{{ $daylog->slug }}/tasks/create"
                    role="button" class="btn btn-primary">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    Create Task
                </a>
            </p>
        </div>
    </div>

@endsection