routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::model('daylogs', 'Daylog');
Route::model('tasks', 'Task');

Route::bind('daylogs', function($value, $route) {
    return App\Daylog::whereSlug($value)->first();
});

Route::bind('tasks', function($value, $route) {
    return App\Task::whereSlug($value)->first();
});

Route::resource('daylogs', 'DaylogController');
Route::resource('daylogs.tasks', 'TaskController');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

resources/views/layouts/alert-danger.blade.php
<div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <p>{{ $errorMessage }}</p>
</div>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            @if (Session::has('message'))
                <div class="alert alert-info alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <p>{{ Session::get('message') }}</p>
                </div>
            @endif

            @yield('content')
        </div>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/daylog.blade.php
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>{{ $method }} Day Log</h3>
    </div>

    <div class="panel-body">
        {!! Form::model( $model, $formAttributes) !!}
            <div class="form-horizontal">
                @include('daylogs/partials/_form',
                    (isset($partialsAttributes) ? $partialsAttributes : []))
            </div>
        {!! Form::close() !!}
    </div>

    @if (!isset($isView))
        <div class="panel-footer">
            <p class="text-center">
                <a href="{{ route('daylogs.index') }}" role="button" class="btn btn-primary">
                    Back
                </a>
            </p>
        </div>
    @endif
</div>

resources/views/layouts/task.blade.php
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>
            {{ $method }} Task<br/>
            <small>Day Log "<em>{{ $daylog->title }}</em>"</small>
        </h3>
    </div>

    <div class="panel-body">
        {!! Form::model( $model, $formAttributes) !!}
            <div class="form-horizontal">
                @include('tasks/partials/_form',
                    (isset($partialsAttributes) ? $partialsAttributes : []))
            </div>
        {!! Form::close() !!}
    </div>

    <div class="panel-footer">
        <p class="text-center">
            <a href="{{ route('daylogs.show', $daylog->slug) }}"
                role="button" class="btn btn-primary">
                Back
            </a>
        </p>
    </div>
</div>